#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum WHa_SpaceAmenities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("24-Hour Access", 6)]
		_24HourAccess = 959040011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Air Cooled", 11)]
		AirCooled = 959040005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bluetooth Lock", 8)]
		BluetoothLock = 959040003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Climate Control", 0)]
		ClimateControl = 127620000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Covered Parking", 2)]
		CoveredParking = 127620005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dumpster Access", 16)]
		DumpsterAccess = 959040008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Electricity In Unit", 10)]
		ElectricityInUnit = 127620003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Elevator Access", 15)]
		ElevatorAccess = 959040007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("First Floor", 14)]
		FirstFloor = 959040006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Heated Only", 12)]
		HeatedOnly = 127620002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Humidity Control", 13)]
		HumidityControl = 127620001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indoor Drive Up Access", 17)]
		IndoorDriveUpAccess = 959040009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Key On File", 7)]
		KeyOnFile = 959040002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Non-Climate Control", 1)]
		NonClimateControl = 127620008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outdoor Drive Up Access", 18)]
		OutdoorDriveUpAccess = 959040010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pallet Deliveries", 5)]
		PalletDeliveries = 959040001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Parcel Acceptance", 4)]
		ParcelAcceptance = 127620007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Uncovered Parking", 3)]
		UncoveredParking = 127620006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wifi", 9)]
		Wifi = 959040004,
	}
}
#pragma warning restore CS1591
